# This is a randomizer file for the Simple Randomizer Maker.
# This file must be named randomizer.py in order to work.
# For more information on what each variable means, see "Readme (Tutorial).md"

from classes import *

def value(name):
	for att in Attributes:
		if att.name == name:
			return att
	print("This attribute does not exist: "+name)
	return None

########################
# EDIT BELOW THIS LINE #
########################

Program_Name = "Snowboard Kids Randomizer - v0.1.0"
Rom_Name = "Snowboard Kids (USA)"
Rom_File_Format = "z64"
Rom_Hash = ["020FB906"]
About_Page_Text = "This is a standard randomizer for Snowboard Kids made using Simple Randomizer Maker. This randomizer won't correct the CRC upon creating a seed and is currently in Beta. Read the 'README.txt' for further details on using this Randomizer in particular. ~ Created by Stingerman06/Chagmen Lietons"
Timeout = 0
Slow_Mode = False

Attributes = [ #116 Attributes to modify
	Attribute( #Rookie Mt. Character
		name="Rookie Mt. P1",
		addresses=[0x000DD0E8],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Track Racers"],
	),
	Attribute( #Rookie Mt. Character
		name="Rookie Mt. P2",
		addresses=[0x000DD0E9],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Track Racers"],
	),
	Attribute( #Rookie Mt. Character
		name="Rookie Mt. P3",
		addresses=[0x000DD0EA],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Track Racers"],
	),
	Attribute( #Rookie Mt. Character
		name="Rookie Mt. P4",
		addresses=[0x000DD0EB],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Track Racers"],
	),
	Attribute( #Big Snowman Character
		name="Big Snowman P1",
		addresses=[0x000DD0C4],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Track Racers"],
	),
	Attribute( #Big Snowman Character
		name="Big Snowman P2",
		addresses=[0x000DD0C5],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Track Racers"],
	),
	Attribute( #Big Snowman Character
		name="Big Snowman P3",
		addresses=[0x000DD0C6],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Track Racers"],
	),
	Attribute( #Big Snowman Character
		name="Big Snowman P4",
		addresses=[0x000DD0C7],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Track Racers"],
	),
	Attribute( #Sunset Rock Character
		name="Sunset Rock P1",
		addresses=[0x000DD0C8],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Track Racers"],
	),
	Attribute( #Sunset Rock Character
		name="Sunset Rock P2",
		addresses=[0x000DD0C9],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Track Racers"],
	),
	Attribute( #Sunset Rock Character
		name="Sunset Rock P3",
		addresses=[0x000DD0CA],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Track Racers"],
	),
	Attribute( #Sunset Rock Character
		name="Sunset Rock P4",
		addresses=[0x000DD0CB],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Track Racers"],
	),
	Attribute( #Night Highway Character
		name="Night Highway P1",
		addresses=[0x000DD0CC],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Track Racers"],
	),
	Attribute( #Night Highway Character
		name="Night Highway P2",
		addresses=[0x000DD0CD],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Track Racers"],
	),
	Attribute( #Night Highway Character
		name="Night Highway P3",
		addresses=[0x000DD0CE],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Track Racers"],
	),
	Attribute( #Night Highway Character
		name="Night Highway P4",
		addresses=[0x000DD0CF],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Track Racers"],
	),
	Attribute( #Grass Valley Character
		name="Grass Valley P1",
		addresses=[0x000DD0D0],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Track Racers"],
	),
	Attribute( #Grass Valley Character
		name="Grass Valley P2",
		addresses=[0x000DD0D1],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Track Racers"],
	),
	Attribute( #Grass Valley Character
		name="Grass Valley P3",
		addresses=[0x000DD0D2],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Track Racers"],
	),
	Attribute( #Grass Valley Character
		name="Grass Valley P4",
		addresses=[0x000DD0D3],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Track Racers"],
	),
	Attribute( #Dizzy-Land Character
		name="Dizzy-Land P1",
		addresses=[0x000DD0D4],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Track Racers"],
	),
	Attribute( #Dizzy-Land Character
		name="Dizzy-Land P2",
		addresses=[0x000DD0D5],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Track Racers"],
	),
	Attribute( #Dizzy-Land Character
		name="Dizzy-Land P3",
		addresses=[0x000DD0D6],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Track Racers"],
	),
	Attribute( #Dizzy-Land Character
		name="Dizzy-Land P4",
		addresses=[0x000DD0D7],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Track Racers"],
	),
	Attribute( #Quicksand Valley Character
		name="Quicksand Valley P1",
		addresses=[0x000DD0D8],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Track Racers"],
	),
	Attribute( #Quicksand Valley Character
		name="Quicksand Valley P2",
		addresses=[0x000DD0D9],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Track Racers"],
	),
	Attribute( #Quicksand Valley Character
		name="Quicksand Valley P3",
		addresses=[0x000DD0DA],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Track Racers"],
	),
	Attribute( #Quicksand Valley Character
		name="Quicksand Valley P4",
		addresses=[0x000DD0DB],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Track Racers"],
	),
	Attribute( #Silver Mt. Character
		name="Silver Mt. P1",
		addresses=[0x000DD0DC],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Track Racers"],
	),
	Attribute( #Silver Mt. Character
		name="Silver Mt. P2",
		addresses=[0x000DD0DD],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Track Racers"],
	),
	Attribute( #Silver Mt. Character
		name="Silver Mt. P3",
		addresses=[0x000DD0DE],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Track Racers"],
	),
	Attribute( #Silver Mt. Character
		name="Silver Mt. P4",
		addresses=[0x000DD0DF],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Track Racers"],
	),
	Attribute( #Ninja Land Character
		name="Ninja Land P1",
		addresses=[0x000DD0E4],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Track Racers"],
	),
	Attribute( #Ninja Land Character
		name="Ninja Land P2",
		addresses=[0x000DD0E5],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Track Racers"],
	),
	Attribute( #Ninja Land Character
		name="Ninja Land P3",
		addresses=[0x000DD0E6],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Track Racers"],
	),
	Attribute( #Ninja Land Character
		name="Ninja Land P4",
		addresses=[0x000DD0E7],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Track Racers"],
	),
    Attribute( #Track 01 - (Orignially Rookie Mt.)
		name="Rookie Mt. Track",
		addresses=[0x000B4021, 0x000B4037, 0x000B404D, 0x000B4063],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5, 6, 8, 9],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Randomize Tracks"],
    ),
    Attribute( #Track 02 - (Orignially Big Snowman)
		name="Big Snowman Track",
		addresses=[0x000B4023, 0x000B4039, 0x000B404F, 0x000B4065],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5, 6, 8, 9],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Randomize Tracks"],
    ),
    Attribute( #Track 03 - (Orignially Sunset Rock)
		name="Sunset Rock Track",
		addresses=[0x000B4025, 0x000B403B, 0x000B4051, 0x000B4067],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5, 6, 8, 9],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Randomize Tracks"],
    ),
    Attribute( #Track 04 - (Orignially Night Highway)
		name="Night Highway Track",
		addresses=[0x000B4027, 0x000B403D, 0x000B4053, 0x000B4069],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5, 6, 8, 9],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Randomize Tracks"],
    ),
    Attribute( #Track 05 - (Orignially Grass Valley)
		name="Grass Valley Track",
		addresses=[0x000B4029, 0x000B403F, 0x000B4055, 0x000B406B],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5, 6, 8, 9],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Randomize Tracks"],
    ),
    Attribute( #Track 06 - (Orignially Dizzy-Land)
		name="Dizzy-Land Track",
		addresses=[0x000B402B, 0x000B4041, 0x000B4057, 0x000B406D],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5, 6, 8, 9],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Randomize Tracks"],
    ),
    Attribute( #Track 07 - (Orignially Quicksand Valley)
		name="Quicksand Valley Track",
		addresses=[0x000B4043, 0x000B4059, 0x000B406F],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5, 6, 8, 9],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Randomize Tracks"],
    ),
    Attribute( #Track 08 - (Orignially Silver Mt.)
		name="Silver Mt. Track",
		addresses=[0x000B405B, 0x000B4071],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5, 6, 8, 9],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Randomize Tracks"],
    ),
    Attribute( #Track 09 - (Orignially Ninja Land)
		name="Ninja Land Track",
		addresses=[0x000B4073],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5, 6, 8, 9],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Randomize Tracks"],
    ),
    Attribute( #Track 10 - (Orignially Animal Land)
		name="Animal Land Track",
		addresses=[0x000B4081],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Randomize M Tracks"],
    ),
    Attribute( #Track M1 - (Orignially Rookie Mt.) - Minigame map
		name="Rookie Mt. Minigames",
		addresses=[0x000B4079],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5, 6, 8, 9],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Randomize M Tracks"],
    ),
    Attribute( #Track M2 - (Orignially Big Snowman) - Minigame map
		name="Big Snowman Minigames",
		addresses=[0x000B407B],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5, 6, 8, 9],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Randomize M Tracks"],
    ),
    Attribute( #Track M3 - (Orignially Sunset Rock) - Minigame map
		name="Sunset Rock Minigames",
		addresses=[0x000B407D],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 1, 2, 3, 4, 5, 6, 8, 9],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Randomize M Tracks"],
    ),
    Attribute( #This is a hotfix for the menu cursor when randomizing any tracks. Update addresses here when/if a discovery occurs for misplaced cursors.
		name="Hotfixes",
		addresses=[0x00003DE3, 0x000069DB, 0x00006A17, 0x00006AA1, 0x0000721D, 0x0000724D, 0x000096BB],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[0, 5],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=["Randomize Tracks", "Randomize M Tracks"],
    ),
    Attribute( #This is a hotfix for the menu cursor when randomizing any tracks. Update addresses here when/if a discovery occurs for misplaced cursors.
		name="Hotfixes - Shopping Overflow Fix",
		addresses=[0x0002F6FC],
		number_of_bytes=1,
		is_little_endian=False,
		possible_values=[30],
		min_value=None,
		max_value=None,
		min_max_interval=None,
		lock_if_enabled=None,
		lock_unless_enabled=None,
    ),
	Attribute( #Freestyle 1 Price
		name="Freestyle 1 Price",
		addresses=[0x000B40B0],
		number_of_bytes=4,
		is_little_endian=False,
		possible_values=None,
		min_value=1,
		max_value=1200,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["Randomize Board Prices"],
	),
	Attribute( #Freestyle 2 Price
		name="Freestyle 2 Price",
		addresses=[0x000B40BC],
		number_of_bytes=4,
		is_little_endian=False,
		possible_values=None,
		min_value=2,
		max_value=12000,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["Randomize Board Prices"],
	),
	Attribute( #Freestyle 3 Price
		name="Freestyle 3 Price",
		addresses=[0x000B40C8],
		number_of_bytes=4,
		is_little_endian=False,
		possible_values=None,
		min_value=3,
		max_value=24000,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["Randomize Board Prices"],
	),
	Attribute( #All-Around 1 Price
		name="All-Around 1 Price",
		addresses=[0x000B40B8],
		number_of_bytes=4,
		is_little_endian=False,
		possible_values=None,
		min_value=1,
		max_value=1000,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["Randomize Board Prices"],
	),
	Attribute( #All-Around 2 Price
		name="All-Around 2 Price",
		addresses=[0x000B40C0],
		number_of_bytes=4,
		is_little_endian=False,
		possible_values=None,
		min_value=2,
		max_value=10000,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["Randomize Board Prices"],
	),
	Attribute( #All-Around 3 Price
		name="All-Around 3 Price",
		addresses=[0x000B40CC],
		number_of_bytes=4,
		is_little_endian=False,
		possible_values=None,
		min_value=3,
		max_value=20000,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["Randomize Board Prices"],
	),
	Attribute( #Alpine 1 Price
		name="Alpine 1 Price",
		addresses=[0x000B40B4],
		number_of_bytes=4,
		is_little_endian=False,
		possible_values=None,
		min_value=1,
		max_value=1100,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["Randomize Board Prices"],
	),
	Attribute( #Alpine 2 Price
		name="Alpine 2 Price",
		addresses=[0x000B40C4],
		number_of_bytes=4,
		is_little_endian=False,
		possible_values=None,
		min_value=2,
		max_value=11000,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["Randomize Board Prices"],
	),
	Attribute( #Alpine 3 Price
		name="Alpine 3 Price",
		addresses=[0x000B40D0],
		number_of_bytes=4,
		is_little_endian=False,
		possible_values=None,
		min_value=3,
		max_value=22000,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["Randomize Board Prices"],
	),
	Attribute( #Special Star Price
		name="Special Star Price",
		addresses=[0x000B40D4],
		number_of_bytes=4,
		is_little_endian=False,
		possible_values=None,
		min_value=2,
		max_value=80000,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["Randomize Board Prices"],
	),
	Attribute( #Special Feather Price
		name="Special Feather Price",
		addresses=[0x000B40D8],
		number_of_bytes=4,
		is_little_endian=False,
		possible_values=None,
		min_value=3,
		max_value=100000,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["Randomize Board Prices"],
	),
	Attribute( #Special Ice Price
		name="Special Ice Price",
		addresses=[0x000B40DC],
		number_of_bytes=4,
		is_little_endian=False,
		possible_values=None,
		min_value=1,
		max_value=1000,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["Randomize Board Prices"],
	),
    Attribute( #Slash Board Type/Level in Rookie Mt.
        name="Slash Board T 1",
        addresses=[0x000DD17C],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Slash Board Type/Level in Big Snowman
        name="Slash Board T 2",
        addresses=[0x000DD0EC],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Slash Board Type/Level in Sunset Rock
        name="Slash Board T 3",
        addresses=[0x000DD0FC],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Slash Board Type/Level in Night Highway
        name="Slash Board T 4",
        addresses=[0x000DD10C],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Slash Board Type/Level in Grass Valley
        name="Slash Board T 5",
        addresses=[0x000DD11C],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Slash Board Type/Level in Dizzy-Land
        name="Slash Board T 6",
        addresses=[0x000DD12C],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Slash Board Type/Level in Quicksand Valley
        name="Slash Board T 7",
        addresses=[0x000DD13C],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Slash Board Type/Level in Silver Mt.
        name="Slash Board T 8",
        addresses=[0x000DD14C],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Slash Board Type/Level in Ninja Land
        name="Slash Board T 9",
        addresses=[0x000DD16C],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Nancy Board Type/Level in Rookie Mt.
        name="Nancy Board T 1",
        addresses=[0x000DD17E],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Nancy Board Type/Level in Big Snowman
        name="Nancy Board T 2",
        addresses=[0x000DD0EE],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Nancy Board Type/Level in Sunset Rock
        name="Nancy Board T 3",
        addresses=[0x000DD0FE],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Nancy Board Type/Level in Night Highway
        name="Nancy Board T 4",
        addresses=[0x000DD10E],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Nancy Board Type/Level in Grass Valley
        name="Nancy Board T 5",
        addresses=[0x000DD11E],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Nancy Board Type/Level in Dizzy-Land
        name="Nancy Board T 6",
        addresses=[0x000DD12E],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Nancy Board Type/Level in Quicksand Valley
        name="Nancy Board T 7",
        addresses=[0x000DD13E],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Nancy Board Type/Level in Silver Mt.
        name="Nancy Board T 8",
        addresses=[0x000DD14E],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Nancy Board Type/Level in Ninja Land
        name="Nancy Board T 9",
        addresses=[0x000DD16E],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Jam Board Type/Level in Rookie Mt.
        name="Jam Board T 1",
        addresses=[0x000DD180],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Jam Board Type/Level in Big Snowman
        name="Jam Board T 2",
        addresses=[0x000DD0F0],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Jam Board Type/Level in Sunset Rock
        name="Jam Board T 3",
        addresses=[0x000DD100],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Jam Board Type/Level in Night Highway
        name="Jam Board T 4",
        addresses=[0x000DD110],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Jam Board Type/Level in Grass Valley
        name="Jam Board T 5",
        addresses=[0x000DD120],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Jam Board Type/Level in Dizzy-Land
        name="Jam Board T 6",
        addresses=[0x000DD130],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Jam Board Type/Level in Quicksand Valley
        name="Jam Board T 7",
        addresses=[0x000DD140],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Jam Board Type/Level in Silver Mt.
        name="Jam Board T 8",
        addresses=[0x000DD150],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Jam Board Type/Level in Ninja Land
        name="Jam Board T 9",
        addresses=[0x000DD170],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Linda Board Type/Level in Rookie Mt.
        name="Linda Board T 1",
        addresses=[0x000DD182],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Linda Board Type/Level in Big Snowman
        name="Linda Board T 2",
        addresses=[0x000DD0F2],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Linda Board Type/Level in Sunset Rock
        name="Linda Board T 3",
        addresses=[0x000DD102],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Linda Board Type/Level in Night Highway
        name="Linda Board T 4",
        addresses=[0x000DD112],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Linda Board Type/Level in Grass Valley
        name="Linda Board T 5",
        addresses=[0x000DD122],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Linda Board Type/Level in Dizzy-Land
        name="Linda Board T 6",
        addresses=[0x000DD132],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Linda Board Type/Level in Quicksand Valley
        name="Linda Board T 7",
        addresses=[0x000DD142],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Linda Board Type/Level in Silver Mt.
        name="Linda Board T 8",
        addresses=[0x000DD152],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Linda Board Type/Level in Ninja Land
        name="Linda Board T 9",
        addresses=[0x000DD172],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Tommy Board Type/Level in Rookie Mt.
        name="Tommy Board T 1",
        addresses=[0x000DD184],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Tommy Board Type/Level in Big Snowman
        name="Tommy Board T 2",
        addresses=[0x000DD0F4],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Tommy Board Type/Level in Sunset Rock
        name="Tommy Board T 3",
        addresses=[0x000DD104],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Tommy Board Type/Level in Night Highway
        name="Tommy Board T 4",
        addresses=[0x000DD114],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Tommy Board Type/Level in Grass Valley
        name="Tommy Board T 5",
        addresses=[0x000DD124],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Tommy Board Type/Level in Dizzy-Land
        name="Tommy Board T 6",
        addresses=[0x000DD134],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Tommy Board Type/Level in Quicksand Valley
        name="Tommy Board T 7",
        addresses=[0x000DD144],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Tommy Board Type/Level in Silver Mt.
        name="Tommy Board T 8",
        addresses=[0x000DD154],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Tommy Board Type/Level in Ninja Land
        name="Tommy Board T 9",
        addresses=[0x000DD174],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Shinobin Board Type/Level in Rookie Mt.
        name="Shinobin Board T 1",
        addresses=[0x000DD186],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Shinobin Board Type/Level in Big Snowman
        name="Shinobin Board T 2",
        addresses=[0x000DD0F6],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Shinobin Board Type/Level in Sunset Rock
        name="Shinobin Board T 3",
        addresses=[0x000DD106],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Shinobin Board Type/Level in Night Highway
        name="Shinobin Board T 4",
        addresses=[0x000DD116],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Shinobin Board Type/Level in Grass Valley
        name="Shinobin Board T 5",
        addresses=[0x000DD126],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Shinobin Board Type/Level in Dizzy-Land
        name="Shinobin Board T 6",
        addresses=[0x000DD136],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Shinobin Board Type/Level in Quicksand Valley
        name="Shinobin Board T 7",
        addresses=[0x000DD146],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Shinobin Board Type/Level in Silver Mt.
        name="Shinobin Board T 8",
        addresses=[0x000DD156],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
    Attribute( #Shinobin Board Type/Level in Ninja Land
        name="Shinobin Board T 9",
        addresses=[0x000DD176],
        number_of_bytes=1,
		is_little_endian=False,
		possible_values=None,
		min_value=0,
		max_value=14,
		min_max_interval=1,
		lock_if_enabled=None,
		lock_unless_enabled=["NPC Boards"],
    ),
]

Required_Rules = []

Optional_Rulesets = [ #11/14 Total Rulesets - TODO: Clean up the entire code and change rulesets around for balancing purposes.
	Ruleset( #Randomizes the Board Prices when making a purchase in the shop - "Randomize Board Prices"
		name="Randomize Board Prices",
		description="This randomizes board prices for all boards in the shop(up to the original max price because I'm generous).",
		rules=[],
		must_be_enabled=None,
		must_be_disabled=None,
    ),
    Ruleset( #Balance Board Prices - "Balance Prices"
        name="Balance Prices",
        description="This will make sure the prices are higher for each board rather than random.",
        rules=[
            Rule( #Balance out freestyle 2 and 3 board Prices
                description="Balance out freestyle 2 and 3 board Prices",
                left_side=value("Freestyle 2 Price"),
                rule_type="<",
                right_side=value("Freestyle 3 Price"),
            ),
            Rule( #Balance out freestyle 1 and 2 board Prices
                description="Balance out freestyle 1 and 2 board Prices",
                left_side=value("Freestyle 1 Price"),
                rule_type="<",
                right_side=value("Freestyle 2 Price"),
            ),
            Rule( #Balance out all-around 2 and 3 board Prices
                description="Balance out all-around 2 and 3 board Prices",
                left_side=value("All-Around 2 Price"),
                rule_type="<",
                right_side=value("All-Around 3 Price"),
            ),
            Rule( #Balance out all-around 1 and 2 board Prices
                description="Balance out all-around 1 and 2 board Prices",
                left_side=value("All-Around 1 Price"),
                rule_type="<",
                right_side=value("All-Around 2 Price"),
            ),
            Rule( #Balance out alpine 2 and 3 board Prices
                description="Balance out alpine 2 and 3 board Prices",
                left_side=value("Alpine 2 Price"),
                rule_type="<",
                right_side=value("Alpine 3 Price"),
            ),
            Rule( #Balance out alpine 1 and 2 board Prices
                description="Balance out alpine 1 and 2 board Prices",
                left_side=value("Alpine 1 Price"),
                rule_type="<",
                right_side=value("Alpine 2 Price"),
            ),
            Rule( #Balance out Feather and Star board Prices
                description="Balance out Feather and Star board Prices",
                left_side=value("Special Star Price"),
                rule_type="<",
                right_side=value("Special Feather Price"),
            ),
            Rule( #Balance out Ice and Feather board Prices
                description="Balance out Ice and Star board Prices",
                left_side=value("Special Ice Price"),
                rule_type="<",
                right_side=value("Special Star Price"),
            ),
        ],
        must_be_enabled=["Randomize Board Prices"],
        must_be_disabled=None,
    ),
	Ruleset( #Randomize Track Racers Enabler - "Track Racers"
		name="Track Racers",
		description="This randomizes all characters to race against.",
		rules=[],
		must_be_enabled=None,
		must_be_disabled=None,
    ),
	Ruleset( #Excludes Shinobin from being selected in the first 8 tracks - "Exclude Shinobin"
		name="Exclude Shinobin",
		description="Does not allow Shinobin to be included in the pool outside of Ninja Land.",
		rules=[
            Rule(
                description=" ",
                left_side=[value("Rookie Mt. P1"), value("Rookie Mt. P2"), value("Rookie Mt. P3"), value("Rookie Mt. P4"), value("Big Snowman P1"), value("Big Snowman P2"), value("Big Snowman P3"), value("Big Snowman P4"), value("Sunset Rock P1"), value("Sunset Rock P2"), value("Sunset Rock P3"), value("Sunset Rock P4"), value("Night Highway P1"), value("Night Highway P2"), value("Night Highway P3"), value("Night Highway P4"), value("Grass Valley P1"), value("Grass Valley P2"), value("Grass Valley P3"), value("Grass Valley P4"), value("Dizzy-Land P1"), value("Dizzy-Land P2"), value("Dizzy-Land P3"), value("Dizzy-Land P4"), value("Quicksand Valley P1"), value("Quicksand Valley P2"), value("Quicksand Valley P3"), value("Quicksand Valley P4"), value("Silver Mt. P1"), value("Silver Mt. P2"), value("Silver Mt. P3"), value("Silver Mt. P4")],
                rule_type="<",
                right_side=5,
            ),
        ],
		must_be_enabled=["Track Racers"],
		must_be_disabled=None,
    ),
	Ruleset( #Prevents any character from showing up more than once per track - "No Duplicates"
		name="No Duplicates",
		description="Don't allow clones to show up in the races. Example 2 Jam's.",
		rules=[
            Rule( #No Rookie Mt. Duplicate Characters
                description="Different Racers in Rookie Mt.",
                left_side=[value("Rookie Mt. P1"), value("Rookie Mt. P2"), value("Rookie Mt. P3"), value("Rookie Mt. P4")],
                rule_type="!=",
                right_side=None,
            ),
            Rule( #No Big Snowman Duplicate Characters
                description="Different Racers in Big Snowman",
                left_side=[value("Big Snowman P1"), value("Big Snowman P2"), value("Big Snowman P3"), value("Big Snowman P4")],
                rule_type="!=",
                right_side=None,
            ),
            Rule( #No Sunset Rock Duplicate Characters
                description="Different Racers in Sunset Rock",
                left_side=[value("Sunset Rock P1"), value("Sunset Rock P2"), value("Sunset Rock P3"), value("Sunset Rock P4")],
                rule_type="!=",
                right_side=None,
            ),
            Rule( #No Night Highway Duplicate Characters
                description="Different Racers in Night Highway",
                left_side=[value("Night Highway P1"), value("Night Highway P2"), value("Night Highway P3"), value("Night Highway P4")],
                rule_type="!=",
                right_side=None,
            ),
            Rule( #No Grass Valley Duplicate Characters
                description="Different Racers in Grass Valley",
                left_side=[value("Grass Valley P1"), value("Grass Valley P2"), value("Grass Valley P3"), value("Grass Valley P4")],
                rule_type="!=",
                right_side=None,
            ),
            Rule( #No Dizzy-Land Duplicate Characters
                description="Different Racers in Dizzy-Land",
                left_side=[value("Dizzy-Land P1"), value("Dizzy-Land P2"), value("Dizzy-Land P3"), value("Dizzy-Land P4")],
                rule_type="!=",
                right_side=None,
            ),
            Rule( #No Quicksand Valley Duplicate Characters
                description="Different Racers in Quicksand Valley",
                left_side=[value("Quicksand Valley P1"), value("Quicksand Valley P2"), value("Quicksand Valley P3"), value("Quicksand Valley P4")],
                rule_type="!=",
                right_side=None,
            ),
            Rule( #No Silver Mt. Duplicate Characters
                description="Different Racers in Silver Mt.",
                left_side=[value("Silver Mt. P1"), value("Silver Mt. P2"), value("Silver Mt. P3"), value("Silver Mt. P4")],
                rule_type="!=",
                right_side=None,
            ),
            Rule( #No Ninja Land Duplicate Characters
                description="Different Racers in Ninja Land",
                left_side=[value("Ninja Land P1"), value("Ninja Land P2"), value("Ninja Land P3"), value("Ninja Land P4")],
                rule_type="!=",
                right_side=None,
            ),
        ],
		must_be_enabled="Track Racers",
		must_be_disabled=None,
    ),
    Ruleset( #Randomize Tracks - "Randomize Tracks"
        name="Randomize Tracks",
        description="Randomize the tacks that you race on and use for time trial(can't separate without further knowledge).",
        rules=[],
        must_be_enabled=None,
        must_be_disabled=None,
    ),
    Ruleset( #Randomize Minigame Tracks - "Randomize M Tracks"
        name="Randomize M Tracks",
        description="Randomize the minigame tracks. Notice: The Speed/Shot minigames don't have a valid original location for the Fan/Snowmen placements in other tracks.",
        rules=[],
        must_be_enabled=None,
        must_be_disabled=None,
    ),
    Ruleset( #Prevents Track Repeats - "Track Shuffle"
        name="Track Shuffle",
        description="Prevents duplicate tracks from appearing.",
        rules=[ #This just makes sure all tracks are shuffled instead of being randomly chosen.
            Rule( #Keeps the main tracks shuffled.
                description="You seem familiar",
                left_side=[value("Rookie Mt. Track"), value("Big Snowman Track"), value("Sunset Rock Track"), value("Night Highway Track"), value("Grass Valley Track"), value("Dizzy-Land Track"), value("Quicksand Valley Track"), value("Silver Mt. Track"), value("Ninja Land Track")],
                rule_type="!=",
                right_side=None,
            ),
        ],
        must_be_enabled=["Randomize Tracks"],
        must_be_disabled=None,
    ),
    Ruleset( #Prevents Track Repeats - "M Track Shuffle"
        name="M Track Shuffle",
        description="Prevents duplicate tracks from appearing.",
        rules=[ #This just makes sure all tracks are shuffled instead of being randomly chosen.
            Rule( #Keeps the minigame tracks shuffled.
                description="Shuffle or Boogie",
                left_side=[value("Rookie Mt. Minigames"), value("Big Snowman Minigames"), value("Sunset Rock Minigames")],
                rule_type="!=",
                right_side=None,
            ),
        ],
        must_be_enabled=["Randomize M Tracks"],
        must_be_disabled=None,
    ),
    Ruleset( #Prevents Minigame Track Repeats - "Consistent Tracks"
        name="Consistent Tracks",
        description="This keeps tracks 1, 2 and 3 from being different in the minigames as opposed to the main tracks.",
        rules=[ #This keeps tracks 1, 2 and 3 from being different in the minigames as opposed to the main tracks.
            Rule( #Keeps track one consistent
                description="Keep Rookie Mt.",
                left_side=[value("Rookie Mt. Minigames"), value("Rookie Mt. Track")],
                rule_type="=",
                right_side=None,
            ),
            Rule( #Keeps track two consistent
                description="Keep track two",
                left_side=[value("Big Snowman Minigames"), value("Big Snowman Track")],
                rule_type="=",
                right_side=None,
            ),
            Rule( #Keeps track three consistent
                description="Keep track three",
                left_side=[value("Sunset Rock Minigames"), value("Sunset Rock Track")],
                rule_type="=",
                right_side=None,
            ),
        ],
        must_be_enabled=["Track Shuffle", "M Track Shuffle"],
        must_be_disabled=None,
    ),
    Ruleset( #Randomize NPC Boards - "NPC Boards"
        name="NPC Boards",
        description="This randomizes the NPC board type and level.",
        rules=[],
        must_be_enabled=None,
        must_be_disabled=None,
    ),
    Ruleset( #Balance NPC board levels - "Balanced Boards"
        name="Balanced Boards",
        description="This keeps the boards each and every NPC that races balanced.",
        rules=[
            Rule( #Balanced Rookie Mt. racers
                description="Balanced Rookie Mt. racers",
                left_side=[value("Slash Board T 1"), value("Nancy Board T 1"), value("Jam Board T 1"), value("Linda Board T 1"), value("Tommy Board T 1"), value("Shinobin Board T 1")],
                rule_type="<",
                right_side=3,
            ),
            Rule( #Balanced Big Snowman racers
                description="Balanced Big Snowman racers",
                left_side=[value("Slash Board T 2"), value("Nancy Board T 2"), value("Jam Board T 2"), value("Linda Board T 2"), value("Tommy Board T 2"), value("Shinobin Board T 2")],
                rule_type="<",
                right_side=3,
            ),
            Rule( #Balanced Sunset Rock racers
                description="Balanced Sunset Rock racers",
                left_side=[value("Slash Board T 3"), value("Nancy Board T 3"), value("Jam Board T 3"), value("Linda Board T 3"), value("Tommy Board T 3"), value("Shinobin Board T 3")],
                rule_type="<",
                right_side=3,
            ),
            Rule( #Balanced Night Highway racers
                description="Balanced Night Highway racers",
                left_side=[value("Slash Board T 4"), value("Nancy Board T 4"), value("Jam Board T 4"), value("Linda Board T 4"), value("Tommy Board T 4"), value("Shinobin Board T 4")],
                rule_type="<",
                right_side=6,
            ),
            Rule( #Balanced Night Highway racers MIN
                description="Balanced Night Highway racers MIN",
                left_side=[value("Slash Board T 4"), value("Nancy Board T 4"), value("Jam Board T 4"), value("Linda Board T 4"), value("Tommy Board T 4"), value("Shinobin Board T 4")],
                rule_type=">",
                right_side=2,
            ),
            Rule( #Balanced Grass Valley racers
                description="Balanced Grass Valley racers",
                left_side=[value("Slash Board T 5"), value("Nancy Board T 5"), value("Jam Board T 5"), value("Linda Board T 5"), value("Tommy Board T 5"), value("Shinobin Board T 5")],
                rule_type="<",
                right_side=6,
            ),
            Rule( #Balanced Grass Valley racers MIN
                description="Balanced Grass Valley racers MIN",
                left_side=[value("Slash Board T 5"), value("Nancy Board T 5"), value("Jam Board T 5"), value("Linda Board T 5"), value("Tommy Board T 5"), value("Shinobin Board T 5")],
                rule_type=">",
                right_side=2,
            ),
            Rule( #Balanced Dizzy-Land racers
                description="Balanced Dizzy-Land racers",
                left_side=[value("Slash Board T 6"), value("Nancy Board T 6"), value("Jam Board T 6"), value("Linda Board T 6"), value("Tommy Board T 6"), value("Shinobin Board T 6")],
                rule_type="<",
                right_side=9,
            ),
            Rule( #Balanced Dizzy-Land racers MIN
                description="Balanced Dizzy-Land racers MIN",
                left_side=[value("Slash Board T 6"), value("Nancy Board T 6"), value("Jam Board T 6"), value("Linda Board T 6"), value("Tommy Board T 6"), value("Shinobin Board T 6")],
                rule_type=">",
                right_side=5,
            ),
            Rule( #Balanced Quicksand Valley racers
                description="Balanced Quicksand Valley racers",
                left_side=[value("Slash Board T 7"), value("Nancy Board T 7"), value("Jam Board T 7"), value("Linda Board T 7"), value("Tommy Board T 7"), value("Shinobin Board T 7")],
                rule_type="<",
                right_side=9,
            ),
            Rule( #Balanced Quicksand Valley racers MIN
                description="Balanced Quicksand Valley racers MIN",
                left_side=[value("Slash Board T 7"), value("Nancy Board T 7"), value("Jam Board T 7"), value("Linda Board T 7"), value("Tommy Board T 7"), value("Shinobin Board T 7")],
                rule_type=">",
                right_side=5,
            ),
            Rule( #Balanced Silver Mt. racers
                description="Balanced Silver Mt. racers",
                left_side=[value("Slash Board T 8"), value("Nancy Board T 8"), value("Jam Board T 8"), value("Linda Board T 8"), value("Tommy Board T 8"), value("Shinobin Board T 8")],
                rule_type="<",
                right_side=12,
            ),
            Rule( #Balanced Silver Mt. racers MIN
                description="Balanced Silver Mt. racers MIN",
                left_side=[value("Slash Board T 8"), value("Nancy Board T 8"), value("Jam Board T 8"), value("Linda Board T 8"), value("Tommy Board T 8"), value("Shinobin Board T 8")],
                rule_type=">",
                right_side=5,
            ),
            Rule( #Balanced Ninja Land racers MIN
                description="Balanced Ninja Land racers MIN",
                left_side=[value("Slash Board T 9"), value("Nancy Board T 9"), value("Jam Board T 9"), value("Linda Board T 9"), value("Tommy Board T 9")],
                rule_type=">",
                right_side=8,
            ),
            Rule( #Shinobin on Ninja Land base Random
                description="Shinobin on Ninja Land base Random",
                left_side=[value("Shinobin Board T 9")],
                rule_type=">",
                right_side=11,
            ),
        ],
        must_be_enabled=["NPC Boards"],
        must_be_disabled=None,
    ),
]
